[package]
name = "portable-chair"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
fromsoftware-shared.workspace = true
eldenring.workspace = true
windows = { version = "0.61", features = [
    "Win32_System_SystemServices",
] }

[lib]
crate-type = ["cdylib"]
